### ISSUE TITLE
Memory Leak on the gstreamer example

### ISSUE THREAD

**Issue by icemanaf** [sepfy/pear#10]
When running the gstreamer example on a Pi Zero W , I noticed that the application was slowly but surely increasing it's memory usage, from around 7% as displayed on the top command, to around 70% when the PI crashed after 15 minutes or so. The fix is very simple, you need to unmap the gst buffer once you are done with it.

I've opened a  PR https://github.com/sepfy/pear/pull/9

**Comment by sepfy** [comment]
OK! Merged. Thanks~
