### ISSUE TITLE
Working over TURN

### ISSUE THREAD

**Issue by aldoshkin** [sepfy/pear#16]
Hello @sepfy !
I am trying to use Pear to work over TURN server. I use Coturn but unable to make it work. Do you have any experience with this? Maybe you have example?
Thanks!

**Comment by sepfy** [comment]
Sorry. I have no experience with Coturn.

**Comment by aldoshkind** [comment]
Hello!
I managed to make libpear work through coturn, you can find necessary changes here: 
https://github.com/aldoshkind/pear/blob/416c21f552313dc47dc18f10744ec9459662ad85/src/peer_connection.c#L318

Since solution found I think we can close the issue.
